package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/fatihbaltaci/GoDrop/internal/wizard"
)

// Changing one thing about an installation that already exists is a different
// job from setting one up: the token, the uploads and every answer nobody
// mentioned stay exactly as they are, and only what was named on the command
// line moves.

// settingFlags maps the flags that describe an installation onto the variables
// the service reads. A flag not in here does not change a configuration.
var settingFlags = []struct {
	flag string
	key  string
	// value renders the flag's value as the variable's, which is not always
	// the same thing: a port is written as a listen address.
	value func(string) string
	// validate rejects an answer here rather than in a service that will not
	// come back up.
	validate func(string) error
}{
	{"base-url", "GODROP_BASE_URL", wizard.NormalizeBaseURL, wizard.ValidateBaseURL},
	{"port", "GODROP_ADDR", func(v string) string { return ":" + v }, wizard.ValidatePort},
	{"max-file-size", "GODROP_MAX_FILE_SIZE", nil, wizard.ValidateSize},
	{"max-total-size", "GODROP_MAX_TOTAL_SIZE", nil, wizard.ValidateOptionalSize},
	{"retention", "GODROP_RETENTION", nil, wizard.ValidateRetention},
	{"tls", "GODROP_TLS", nil, validateTLSChoice},
	{"tls-cert", "GODROP_TLS_CERT", nil, wizard.ValidateFile},
	{"tls-key", "GODROP_TLS_KEY", nil, wizard.ValidateFile},
}

// validateTLSChoice accepts the answers the certificate question offers.
func validateTLSChoice(v string) error {
	switch v {
	case wizard.TLSAuto, wizard.TLSFile, wizard.TLSProxy, wizard.TLSNone:
		return nil
	}
	return fmt.Errorf("%q is not one of auto, file, proxy, none", v)
}

// changedSettings collects the settings named on this command line.
func changedSettings(cmd *cobra.Command) (map[string]string, error) {
	changes := map[string]string{}
	for _, s := range settingFlags {
		if !cmd.Flags().Changed(s.flag) {
			continue
		}
		value, _ := cmd.Flags().GetString(s.flag)
		if s.validate != nil {
			if err := s.validate(value); err != nil {
				return nil, fmt.Errorf("--%s: %w", s.flag, err)
			}
		}
		if s.value != nil {
			value = s.value(value)
		}
		changes[s.key] = value
	}
	if cmd.Flags().Changed("telemetry") {
		on, _ := cmd.Flags().GetBool("telemetry")
		if on {
			// Removing the line is how it is turned back on, since the default
			// is on and an empty value would read as one.
			changes["GODROP_TELEMETRY"] = ""
		} else {
			changes["GODROP_TELEMETRY"] = "off"
		}
	}
	return changes, nil
}

// reconfigure applies those changes to an installation and restarts it into
// them.
func reconfigure(cmd *cobra.Command, out *output, build Build, dir string, changes map[string]string) error {
	envPath := filepath.Join(dir, ".env")
	before := readEnvFile(envPath)

	out.heading("Changing")
	for _, key := range sortedKeys(changes) {
		switch {
		case changes[key] == "" && before[key] == "":
			out.skip("%-22s unchanged", envName(key))
			continue
		case changes[key] == before[key]:
			out.skip("%-22s unchanged", envName(key))
			continue
		}
		out.success("%-22s %s", envName(key), envValue(key, changes[key]))
	}

	updated, err := applyToEnvFile(envPath, changes)
	if err != nil {
		return err
	}

	// The compose file publishes the port, so a new one has to reach it too.
	if err := rewriteCompose(out, dir, updated); err != nil {
		return err
	}

	return upgrade(cmd.Context(), out, build, dir)
}

// rewriteCompose puts a changed port into the file that publishes it.
//
// The file is regenerated from the answers, with one thing read back out of
// the old one first: where the uploads are. An installation from before named
// volumes, or one pointed at a directory on the host, must not be quietly
// moved onto a fresh empty volume.
func rewriteCompose(out *output, dir string, values map[string]string) error {
	// One read answers both questions: whether there is a compose file here,
	// and whether it is one setup wrote. A file this program did not write is
	// not one it gets to rewrite.
	compose := filepath.Join(dir, "docker-compose.yml")
	body, err := os.ReadFile(compose) //nolint:gosec // G304, the path is this package's own
	first, _, _ := strings.Cut(string(body), "\n")
	if err != nil || !strings.Contains(first, "generated by `godrop init`") {
		return nil
	}
	a := answersFrom(values)
	a.Deployment = wizard.DeployCompose
	a.Image = wizard.Defaults().Image
	a.DataDir = hostVolumeIn(string(body))
	a.TLS = values["GODROP_TLS"]

	next := wizard.ComposeFile(a)
	if next == string(body) {
		return nil
	}
	if err := os.WriteFile(compose, []byte(next), 0o644); err != nil { //nolint:gosec // G306, a compose file is not a secret
		return err
	}
	out.success("%-22s %s", "docker-compose.yml", "rewritten for the new port")
	return nil
}

// hostVolumeIn reads the source of the /data mount out of a compose file, and
// answers with an empty string for the named volume every recent setup uses.
func hostVolumeIn(body string) string {
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		source, ok := strings.CutSuffix(line, ":/data")
		if !ok {
			continue
		}
		source = strings.TrimSpace(strings.TrimPrefix(source, "- "))
		if source == "godrop-data" {
			return ""
		}
		return source
	}
	return ""
}

// applyToEnvFile replaces the values it was given and leaves every other line
// where it was, comments and hand edits included. An empty value removes the
// setting, which is how a variable goes back to its default.
func applyToEnvFile(path string, changes map[string]string) (map[string]string, error) {
	data, err := os.ReadFile(path) //nolint:gosec // G304, the path is this package's own
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var out []string
	for _, line := range strings.Split(strings.TrimRight(string(data), "\n"), "\n") {
		key, _, isSetting := strings.Cut(strings.TrimSpace(line), "=")
		key = strings.TrimSpace(key)
		value, changing := changes[key]
		if !isSetting || strings.HasPrefix(strings.TrimSpace(line), "#") || !changing {
			out = append(out, line)
			continue
		}
		seen[key] = true
		if value == "" {
			// The line goes, and the default takes over.
			continue
		}
		out = append(out, key+"="+value)
	}
	for _, key := range sortedKeys(changes) {
		if seen[key] || changes[key] == "" {
			continue
		}
		out = append(out, key+"="+changes[key])
	}
	body := strings.Join(out, "\n") + "\n"
	// 0600: the file still has the token in it. The path is the one this
	// package works out for itself, not one that came in from anywhere.
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil { //nolint:gosec // G703
		return nil, err
	}
	return readEnvFile(path), nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// envName is what the rest of the output calls a setting: the variable
// without its prefix, except for the one whose name would say nothing.
func envName(key string) string {
	if key == "GODROP_ADDR" {
		return "listen port"
	}
	return strings.ToLower(strings.ReplaceAll(strings.TrimPrefix(key, "GODROP_"), "_", " "))
}

// envValue is the same for a value: an address is shown as the port it is.
func envValue(key, value string) string {
	if key == "GODROP_ADDR" {
		return strings.TrimPrefix(value, ":")
	}
	return displayValue(value)
}
