#!/usr/bin/env python3
"""Compose site/logo-lockup.svg from the mark and the wordmark.

The two pieces are the source; the lockup is only a layout of them, so it is
generated rather than maintained by hand. Run: make docs
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / "site"


def inner(svg: str) -> str:
    """Return an SVG's contents, without its wrapper or its title."""
    body = svg.split(">", 1)[1].rsplit("</svg>", 1)[0]
    return re.sub(r"<title>.*?</title>\s*", "", body, flags=re.S).strip()


def main() -> None:
    mark = inner((SITE / "logo.svg").read_text())
    word = inner((SITE / "wordmark.svg").read_text())
    lockup = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 830 240" width="830" height="240" role="img" aria-label="GoDrop">
  <title>GoDrop</title>
  <!-- Generated by scripts/logo.py from logo.svg and wordmark.svg. Edit those. -->
  <g transform="translate(20 10) scale(0.859)">
{mark}
  </g>
  <g transform="translate(256 16)">
{word}
  </g>
</svg>
"""
    (SITE / "logo-lockup.svg").write_text(lockup)
    print("wrote site/logo-lockup.svg")


if __name__ == "__main__":
    main()
